site_url: https://nuxt-store-cms.netlify.app
logo_url: https://nuxt-store-cms.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'products'
    label: 'Products'
    # identifier_field: slug
    folder: 'assets/content/products'
    create: true
    format: 'json'
    slug: '{{fields.slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Slug', name: 'slug', widget: 'number' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Type of Product',
          name: 'type',
          widget: 'select',
          options:
            [
              { label: 'T-Shirt', value: 't-shirts' },
              { label: 'Sweatshirt', value: 'sweatshirts' },
              { label: 'Hoodie', value: 'hoodie' },
            ],
        }
      - {
          label: 'Image',
          name: 'image',
          widget: 'image',
          default: '/static/img/boilerplate.png',
          allow_multiple: false,
        }
      - { label: 'Price', name: 'price', widget: 'number', value_type: 'int', min: 1, max: 90000 }
      - { label: 'Black', name: 'black', widget: 'boolean', default: false }
      - { label: 'New', name: 'new', widget: 'boolean', default: true }
      - { label: 'Structure', name: 'structure', widget: 'string', default: '$$% cotton, $$% polyester' }
      - { label: 'Density', name: 'density', widget: 'string', default: '$$$ g/m²' }
      - {
          label: 'Sizes',
          name: 'sizes',
          widget: 'select',
          multiple: true,
          default: ['S', 'M', 'L'],
          options: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
        }
  # - name: 'projects'
  # identifier_field: name
  # label: 'Projects'
  # label_singular: 'Project'
  # folder: 'assets/content/projects'
  # create: true
  # format: 'json'
  # slug: '{{project_type}}-{{slug}}'
  # preview_path: 'projects/{{slug}}'
  # fields:
  #   - {
  #       label: 'Project Type',
  #       name: 'project_type',
  #       widget: 'select',
  #       default: 'story',
  #       options: [{ label: 'Story', value: 'story' }, { label: 'Photo', value: 'photo' }],
  #     }
  #   - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #   - { label: 'Title', name: 'title', widget: 'string' }
  #   - { label: 'Description', name: 'description', widget: 'string', required: false }
  #   - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #   - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #   - {
  #       label: 'Gallery',
  #       name: 'gallery',
  #       widget: 'list',
  #       required: false,
  #       summary: '{{fields.image}}',
  #       field: { label: 'Image', name: 'image', widget: 'image' },
  #     }
  # - name: 'story_projects'
  #   # identifier_field: name
  #   label: 'Story Projects'
  #   label_singular: 'Story Project'
  #   folder: 'assets/content/stories'
  #   create: true
  #   format: 'json'
  #   slug: '{{slug}}'
  #   preview_path: 'stories/{{slug}}'
  #   # filter: { field: 'project_type', value: 'story' }
  #   fields:
  #     # - { label: 'Project Type', name: 'project_type', widget: 'select', options: ['story', 'photo'] }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
  # - name: 'photo_projects'
  #   # identifier_field: name
  #   label: 'Photo Projects'
  #   label_singular: 'Photo Project'
  #   folder: 'assets/content/photos'
  #   create: true
  #   format: 'json'
  #   slug: '{{slug}}'
  #   preview_path: 'photos/{{slug}}'
  #   # filter: { field: 'project_type', value: 'photo' }
  #   fields:
  #     # - { label: 'Project Type', name: 'project_type', widget: 'select', options: ['story', 'photo'] }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
